replaced the init script

diff --git a/templates/etc/init.d/logstash.RedHat.erb b/templates/etc/init.d/logstash.RedHat.erb
--- a/templates/etc/init.d/logstash.RedHat.erb
+++ b/templates/etc/init.d/logstash.RedHat.erb
@@ -1,11 +1,12 @@
 #! /bin/sh
 #
-#       /etc/rc.d/init.d/logstash
+#   /etc/rc.d/init.d/logstash
 #
-#       Starts Logstash as a daemon
+#   Starts Logstash as a daemon
 #
-# chkconfig: 2345 90 10
+# chkconfig: 2345 20 80
 # description: Starts Logstash as a daemon
+# pidfile: /var/run/logstash.pid
 
 ### BEGIN INIT INFO
 # Provides: logstash
@@ -15,105 +16,48 @@
 # Default-Stop: S 0 1 6
 # Short-Description: Logstash
 # Description: Starts Logstash as a daemon.
-
+# Modified originally from https://gist.github.com/2228905#file_logstash.sh
 ### END INIT INFO
 
-. /etc/rc.d/init.d/functions
-
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
-NAME=logstash
+### CONFIGURATION
+# Amount of memory for Java
+#JAVAMEM=256M
+# Location of logstash files
+LOCATION=/opt/logstash
+PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 DESC="Logstash Daemon"
-DEFAULT=/etc/sysconfig/$NAME
+CONFIG_DIR=/etc/logstash/conf.d/logstash.conf
+LOGFILE=/opt/logstash/logstash.log
+#ARGS="-Xmx$JAVAMEM -Xms$JAVAMEM -jar ${JARNAME} agent --config ${CONFIG_DIR} --log ${LOGFILE} --grok-patterns-path ${PATTERNSPATH}"
+ARGS="bin/logstash -f ${CONFIG_DIR} -l ${LOGFILE}"
+SCRIPTNAME=/etc/init.d/logstash
+PIDFILE=/var/run/logstash.pid
+base=logstash
+### END CONFIGURATION
 
-if [ `id -u` -ne 0 ]; then
-   echo "You need root privileges to run this script"
-   exit 1
-fi
-
-# The following variables can be overwritten in $DEFAULT
-
-export JAVA_HOME=/usr
-
-# Directory where the logstash all in one jar lives
-LS_HOME=/opt/logstash
-
-# Additional Java OPTS
-LS_JAVA_OPTS="-Xmx256m -Djava.io.tmpdir=$LS_HOME/tmp"
-
-# logstash log directory
-LOG_DIR=/var/log/logstash
-
-# logstash configuration directory
-CONF_DIR=/etc/logstash/conf.d
-
-# logstash log file
-LOG_FILE=$LOG_DIR/$NAME.log
-
-# Open File limit
-OPEN_FILES=2048
-
-# Nice level
-NICE=19
-
-# Filter threads
-FILTER_THREADS=1
-
-# End of variables that can be overwritten in $DEFAULT
-
-if [ -f "$DEFAULT" ]; then
-  . "$DEFAULT"
-fi
-
-# Define other required variables
-PID_FILE=/var/run/$NAME.pid
-
-JAVA=`which java`
-JAR="${LS_HOME}/logstash.jar"
-ARGS="${LS_JAVA_OPTS} -jar ${JAR} agent --config ${CONF_DIR} --log ${LOG_FILE} -w ${FILTER_THREADS}"
-
-is_true() {
-    if [ "x$1" = "xtrue" -o "x$1" = "xyes" -o "x$1" = "x1" ] ; then
-        return 0
-    else
-        return 1
-    fi
+# Exit if the package is not installed
+if [ ! -x "$LOCATION/bin/logstash" ]; then
+{
+  echo "Couldn't find logstash"
+  exit 99
 }
+fi
+
+. /etc/init.d/functions
 
 #
 # Function that starts the daemon/service
 #
 do_start()
 {
+  cd $LOCATION && \
+  ($ARGS &) \
+  && success || failure
+}
 
-  if ! is_true "$START" ; then
-    echo "logstash not configured to start, please edit $DEFAULT to enable"
-    exit 0
-  fi
-
-  if [ -z "$JAVA" ]; then
-    echo "no JDK found - $JAVA"
-    exit 1
-  fi
-
-  if ! test -e "${JAR}"; then
-    echo "Daemon $DAEMON doesn't exist"
-    exit 1
-  fi
-
-  if pidofproc -p "$PID_FILE" >/dev/null; then
-    failure
-    exit 99
-  fi
-
-  ulimit -n $OPEN_FILES
-
-  cd $LS_HOME
-  $JAVA $ARGS > /dev/null 1>&1 &
-
-  RETVAL=$?
-  local PID=`pgrep -f "${DAEMON} ${ARGS}"`
-  echo $PID > $PID_FILE
-  success
+set_pidfile()
+{
+  pgrep -f "$ARGS" > $PIDFILE
 }
 
 #
@@ -121,32 +65,46 @@ do_start()
 #
 do_stop()
 {
-    killproc -p $PID_FILE $DAEMON
-    RETVAL=$?
-    echo
-    [ $RETVAL = 0 ] && rm -f ${PID_FILE}
+  pid=`cat $PIDFILE`
+  if checkpid $pid 2>&1; then
+       # TERM first, then KILL if not dead
+       kill -TERM $pid >/dev/null 2>&1
+       usleep 100000
+       if checkpid $pid && sleep 1 &&
+                 checkpid $pid && sleep $delay &&
+                 checkpid $pid ; then
+            kill -KILL $pid >/dev/null 2>&1
+            usleep 100000
+       fi
+   fi
+   checkpid $pid
+   RC=$?
+   [ "$RC" -eq 0 ] && failure $"$base shutdown" || success $"$base shutdown"
+
 }
 
 case "$1" in
   start)
     echo -n "Starting $DESC: "
     do_start
-    touch /var/run/logstash/$NAME
+    touch /var/lock/subsys/logstash
+    set_pidfile
     ;;
   stop)
     echo -n "Stopping $DESC: "
     do_stop
-    rm /var/run/logstash/$NAME
+    rm /var/lock/subsys/logstash
+    rm $PIDFILE
     ;;
   restart|reload)
     echo -n "Restarting $DESC: "
     do_stop
     do_start
+    touch /var/lock/subsys/logstash
+    set_pidfile
     ;;
   status)
-    echo -n "$DESC"
-    status -p $PID_FILE
-    exit $?
+    status -p $PIDFILE
     ;;
   *)
     echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
